spring:
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "${db.url}"
    username: "${db.username}"
    password: "${db.password}"